require 'rubygems'
require 'sinatra/base'
require 'open-uri'
require 'restclient'
require 'builder'
require 'json'
require 'yaml'
require 'haml'
require 'iconv'
# below all gems that arent _default_ in heroku
require 'memcached'
require 'boxcar_api'
require 'couchrest'
require 'instagram'
